### ISSUE TITLE
Discuss : Allowed IPs for system testing

### ISSUE THREAD

**Issue by agithomas** [elastic/elastic-package#1053]
Reference : [Allowed IPs](https://github.com/elastic/elastic-package/blob/main/internal/fields/_static/allowed_geo_ips.txt)

When running the system testing using the GeoIP processor, only if the IP is in the range mentioned in the `allowed_geo_ips.txt`, the geoip processor works 

But, geoIP processor works for pipeline testing without having the above mentioned limitation

Why such a limitation is present?

If there is a reason, shouldn't this limitation be extended to pipeline testing as well?

Pipeline test output is given below. Reference [PR](https://github.com/elastic/integrations/pull/4261): 

```
{
    "expected": [
        {
            "@timestamp": "2022-09-13T05:22:43.429Z",
            "ecs": {
                "version": "8.4.0"
            },
            "event": {
                "action": "login-attempt",
                "category": [
                    "authentication"
                ],
                "dataset": "salesforce.login_rest",
                "kind": "event",
                "module": "salesforce",
                "original": "{\"API_TYPE\":\"f\",\"API_VERSION\":\"9998.0\",\"AUTHENTICATION_METHOD_REFERENCE\":\"\",\"BROWSER_TYPE\":\"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/IP_ADDRESS_REMOVED Safari/537.36\",\"CIPHER_SUITE\":\"ECDHE-RSA-AES256-GCM-SHA384\",\"CLIENT_IP\":\"175.16.199.0\",\"CPU_TIME\":\"63\",\"DB_TOTAL_TIME\":\"93531912\",\"EVENT_TYPE\":\"Login\",\"LOGIN_KEY\":\"NK2oPJrJze8tH+vC\",\"LOGIN_STATUS\":\"LOGIN_NO_ERROR\",\"ORGANIZATION_ID\":\"00D5j000000VI3n\",\"REQUEST_ID\":\"4lGJ1R0ZSWVXwFl1cJIRH-\",\"REQUEST_STATUS\":\"Success\",\"RUN_TIME\":\"156\",\"SESSION_KEY\":\"\",\"SOURCE_IP\":\"175.16.199.0\",\"TIMESTAMP\":\"20220913052243.429\",\"TIMESTAMP_DERIVED\":\"2022-09-13T05:22:43.429Z\",\"TLS_PROTOCOL\":\"TLSv1.2\",\"URI\":\"/index.jsp\",\"URI_ID_DERIVED\":\"s4heK3WbH-lcJIL3-n\",\"USER_ID\":\"0055j000000utlP\",\"USER_ID_DERIVED\":\"0055j000000utlPAAQ\",\"USER_NAME\":\"user@elastic.co\",\"USER_TYPE\":\"Standard\"}",
                "outcome": "success",
                "type": [
                    "info"
                ],
                "url": "/index.jsp"
            },
            "related": {
                "ip": [
                    "175.16.199.0"
                ]
            },
            "salesforce": {
                "login": {
                    "access_mode": "rest",
                    "api": {
                        "type": "Feed",
                        "version": "9998.0"
                    },
                    "client_ip": "175.16.199.0",
                    "cpu_time": 63.0,
                    "db_time": {
                        "total": 93.53191
                    },
                    "event_type": "Login",
                    "key": "NK2oPJrJze8tH+vC",
                    "organization_id": "00D5j000000VI3n",
                    "request_id": "4lGJ1R0ZSWVXwFl1cJIRH-",
                    "request_status": "Success",
                    "run_time": 156.0,
                    "uri_derived_id": "s4heK3WbH-lcJIL3-n",
                    "user_id": "0055j000000utlP"
                }
            },
            "source": {
                "geo": {
                    "city_name": "Changchun",
                    "continent_name": "Asia",
                    "country_iso_code": "CN",
                    "country_name": "China",
                    "location": {
                        "lat": 43.88,
                        "lon": 125.3228
                    },
                    "region_iso_code": "CN-22",
                    "region_name": "Jilin Sheng"
                },
                "ip": "175.16.199.0"
            },
            "tags": [
                "preserve_original_event"
            ],
            "tls": {
                "cipher": "ECDHE-RSA-AES256-GCM-SHA384",
                "version": "1.2",
                "version_protocol": "TLS"
            },
            "user": {
                "email": "user@elastic.co",
                "id": "0055j000000utlPAAQ",
                "roles": "Standard"
            },
            "user_agent": {
                "name": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/IP_ADDRESS_REMOVED Safari/537.36"
            }
        }
    ]
}
```

**Comment by agithomas** [comment]
@jsoriano , i am assigning this issue to you as you are the creator of the `allowed_geo_ips.txt`

**Comment by jsoriano** [comment]
> Why such a limitation is present?

Elasticsearch used to include a geoip database, and update it on runtime. To avoid flakiness, we disabled the automatic updates and used the embedded geoip database. This was still an issue because this embedded database could be updated, affecting test results when updating the version of Elasticsearch used for testing.

Since 8.0.0, Elasticsearch stopped including any geoip database, and downloaded one on runtime. This was a double problem for us:
* We didn't have any embedded database that we could use for testing.
* Results could change even more frequently.

So we decided to embed our own database, a small one generated for testing purpouses only. This way results are consistent for IPs defined there.

> Why such a limitation is present?

If the geoip database doesn't contain information about an IP, the geoip processor silently does nothing, so we cannot reliably detect if a pipeline is not filling the geoip data because of this, or because of some other issue. After including this smaller embedded database, most IPs don't have any data, so we decided to force that when IPs are used, they are obtained from the list of IPs that we know are available in this database.

You can find a brief explanation also here: https://github.com/elastic/elastic-package/blob/main/docs/howto/ingest_geoip.md

**Comment by agithomas** [comment]
@jsoriano , is this a limitation only for elastic-package static testing? 

Can geoIP processor be used in the ingest pipeline with accuracy?
