### ISSUE TITLE
Make test runners output xUnit format

### ISSUE THREAD

**Issue by ycombinator** [elastic/elastic-package#126]
This will allow test results to be captured by Jenkins CI and show up in the Tests tab.

**Comment by mtojek** [comment]
The tricky part is related to the fact we run multiple test commands (one per package), so later on we would have to merge all results.

Another option would be a support for multiple packages at once, so that `elastic-package test` can operate on packages and can collect test results from multiple places.

**Comment by ycombinator** [comment]
I'm going to start looking into this one as it's the first step for a lot of other things we want to do with the test results.
