### ISSUE TITLE
Automate tests in CI for serverless packages

### ISSUE THREAD

**Issue by jlind23** [elastic/elastic-package#1451]
As soon as we have to determine what packages should be run on serverless it will be time to run system tests with them.

We should automate system tests for all packages that opt-in with package spec V3 and have defined capabilities.

**Comment by mrodm** [comment]
Still in progress the PR to add the new pipeline https://github.com/elastic/integrations/pull/8072

But found some issues in [the latest build](https://buildkite.com/elastic/integrations/builds/5475):
- Skipping GeoIP keys did not solve all the issues
    - there are fields/keys that are arrays and they cannot be deleted as the others (threats.enrichments.*.indicators)
    - other packages are using other fields as GeoIP keys out of the ECS
- `azure` package is failing while runnning test pipelines in both `observability` and `security` projects.
- `ti_rapid7_threat_command` package cannot be installed in `observability` project
    - Error: 
      ```
      Error: can't install the package: could not zip-install package; API status code = 500; response body = {"statusCode":500,"error":"Internal Server Error","message":"Encountered 2 errors creating saved objects: [{\"type\":\"security-rule\",\"id\":\"af814670-3279-11ed-93fa-d354b323cd1b\",\"error\":{\"type\":\"unsupported_type\"}},{\"type\":\"security-rule\",\"id\":\"eaecc8f0-6704-11ed-80b2-9bbc46f73b72\",\"error\":{\"type\":\"unsupported_type\"}}]"}
      ```
    - Two versions published with 3.0.0 without any capabilities (1.10.0 and 1.11.0)
      ```shell
       $ curl -s "https://epr.elastic.co/search?package=ti_rapid7_threat_command&spec.min=3.0&all=true" | jq -r '.[]|.version'
      1.10.0
      1.11.0
      ```
- `fleet_server` cannot be installed and it has format_version 3.0.0


@jsoriano @jlind23

**Comment by mrodm** [comment]
`azure` package is also failing with a local Elastic stack using version 8.10.4
```shell
elastic-package stack up -v -d --version 8.10.4
elastic-package test pipeline -v
```

In the schedule-daily job it also fails (8.11.0-SNAPSHOT)
- https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations/detail/main/2951/tests/

With the minimum version supported according to its manifest (^8.6.0) , those tests work:
- https://github.com/elastic/integrations/blob/25849be4f7833b5cf06d3644067f527e587a9068/packages/azure/manifest.yml#L17

**Comment by mrodm** [comment]
Other packages are failing due to probably Serverless is using other GeoIP databases. That different package could cause that new fields would appear in the documents ?

Among these packages:
- cisco_meraki
  ```
  test case failed: one or more problems with fields found in documents: [0] field "client.as.number" is undefined
  [1] field "client.as.organization.name" is undefined
  ```
- modsecurity
  ```
  test case failed: one or more problems with fields found in documents: [0] field "destination.as.asn" is undefined
  [1] field "destination.as.organization_name" is undefined
  ```
- zscaler_zpa
  ```
  test case failed: one or more problems with fields found in documents: [0] field "client.as.asn" is undefined
  [1] field "client.as.organization_name" is undefined
  ```
Examples of

**Comment by mrodm** [comment]
Created issue to add a new parameter or configuration to run or skip comparison of documents:
https://github.com/elastic/ingest-dev/issues/2566

**Comment by mrodm** [comment]
With the PR merged, two new Buildkite pipelines are added (schedule-daily and integrations-serverless), to start testing packages using Serverless projects (observability and security projects) in a daily manner. Just the packages with spec version >= 3.0.0 are going to be tested in the pipeline. Currently, in this pipeline benchmarking and coverage are not calculated.

These job has some differences between the PR job. The first one is that in these executions system tests are not being run. The second one, pipeline tests do not run the comparison of the documents with the sample events, since it cannot be customized the GeoIP database used in Serverless.

There are some packages failing that would need to include more field definitions:
- azure it was also failing in main branch 
- and the packages mentioned here due to some missing field defitions: https://github.com/elastic/elastic-package/issues/1451#issuecomment-1774861044

**Comment by mrodm** [comment]
FYI @elastic/security-external-integrations these three packages are failing due to some missing field definitions in Serverless, could you check those errors ? https://github.com/elastic/elastic-package/issues/1451#issuecomment-1774861044

Not totally sure, but I think this is because in Serverless it is used another GeoIP database (it cannot be specified as we do usually in elastic-package locally) and maybe it could have more information.

**Comment by efd6** [comment]
@mrodm The error messages above don't say which data streams are causing the issue. Do you have that information?

**Comment by mrodm** [comment]
> @mrodm The error messages above don't say which data streams are causing the issue for cisco_meraki and zscalar_zpa. Do you have that information?

Missed to add that information in the previous comment, sorry @efd6 . Data streams for those packages are:
- data stream for cisco_meraki: `log` 
- data stream for zscaler_zpa: `browser_access`
- data stream for modsecurity: `auditlog`


Took those data stream from the JUnit errors from [this build](https://buildkite.com/elastic/integrations-serverless/builds/6) 
![schedule-daily JUnit errors](https://github.com/elastic/elastic-package/assets/5330827/9ddef667-7978-402e-8449-e0b87a99a3e0)
