### ISSUE TITLE
Discuss: where should we keep "import-beats" script

### ISSUE THREAD

**Issue by mtojek** [elastic/elastic-package#152]
The integrations repository should contain only package contents.

Consider moving it to `integrations-extras` or `elastic-package`. The original idea was to remove few months after the final migration.

It's related to the final design of the package registry.

**Comment by mtojek** [comment]
@ycombinator I think this topic needs to be discussed first. Do you have any preferences about the approach? There are multiple options:
1. Leave as is, close this issue or transform it into: rename once everything is migrated.
2. Move under elastic-package and groom the source code (it's not best quality).
3. Hide it in a new repository, let's say: `integrations-extras`.

I'm open to any option, so feel free to propose also other solutions. The ultimate goal was to keep the Integrations repository as pure as possible.

**Comment by ycombinator** [comment]
I have a few questions that will help clarify which option to take:

1. Once all modules are migrated to packages the script should no longer be needed, right? 

2. After the script has been run for a module **the first time**, we don't recommend running it again for the same module, in case there are further updates to the module, right? Instead after that initial migration we suggest manually porting any updates?

If the answer to both these questions is yes, then I am in favor of option 1: leave as-is, since the script will eventually go away after all modules have gone through the initial migration via the script.

Otherwise, I lean towards option 3: move it to a new repository (but not into `elastic-package`) because this script only applies when Beats modules are in the picture and it would be nice if `elastic-package` could deal purely with packages and not "know" anything about Beats modules. Also, the nice thing with option 3 is that it keeps the door open for option 2 in the future, if for some reason there's a concrete (not hypothetical) use case for it. BTW, this doesn't need to be a whole new repository either; we could probably repurpose one of the existing repos (maybe even one of the private ones as Elastic employees are most probably going to be doing the migrations anyway).

**Comment by mtojek** [comment]
> Once all modules are migrated to packages the script should no longer be needed, right?

Yes.
My main concern is that it won't happen. We'll migrate 99% of modules and decide to leave the script just in case.

> After the script has been run for a module the first time, we don't recommend running it again for the same module, in case there are further updates to the module, right? Instead after that initial migration we suggest manually porting any updates, yes?

Yes.
In most (all?) cases the changes introduced to integrations are too complex to analyze by the import-beats script or just refactored.

> Otherwise, I lean towards option 3: move it to a new repository (but not into elastic-package) because this script only applies when Beats modules are in the picture and it would be nice if elastic-package could deal purely with packages and not "know" anything about Beats modules.

I like the idea of "purity" and would like to keep it (hence the idea of moving the script out). I'm not sure if my concern in pt 1. (we won't **finish** the migration process) is not a blocker for option 1. WDYT?

**Comment by ycombinator** [comment]
Thanks. Given what you said, II'm in favor of option 3.

But maybe not just yet.

I did some quick counts and it looks like we have a total of 101 unique modules across Filebeat and Metricbeat today (including X-Pack modules). By comparison, we have a total of 41 Integrations packages. One of these packages is `nginx_ingress_controller`, which does not have an equivalent Beats module. So, in all, there are 61 Beats modules that have not yet been migrated:

```
activemq
aerospike
apache2
appsearch
awsfargate
barracuda
beat
bluecoat
ceph
cloudfoundry
cockroachdb
consul
coredns
couchbase
couchdb
cylance
docker
dropwizard
elasticsearch
envoyproxy
etcd
f5
gcp
golang
googlecloud
graphite
gsuite
http
ibmmq
icinga
imperva
infoblox
istio
jolokia
kibana
kvm
memcached
misp
mssql
munin
mysqlenterprise
netscout
openmetrics
oracle
php_fpm
proofpoint
radware
redisenterprise
snort
snyk
sonicwall
sophos
sql
squid
stan
statsd
tomcat
traefik
uwsgi
vsphere
zscaler
```

So currently the ratio of migrated to not migrated modules is 40:61 or roughly 2:3. In other words, the majority of modules have not yet been migrated to packages yet.

Given this, I think we should go with option 1 for now. This is because this option is the most convenient developer experience at the moment (no need to check out and keep up-to-date one more repo to do a migration).

However, we should revisit this issue after every future release to see if the ratio has flipped. Once enough modules have been migrated so maybe 3:2 or even 3:1 ratio of migrated:not migrated?), I think we can make the import developer experience slightly worse by going with option 3, but gain some cleanup to the integrations repo as a tradeoff.

WDYT?

**Comment by mtojek** [comment]
I didn't expect that the migration progress is 40%  - it looks promissing. In this case I agree to wait a bit to see how many packages will be migrated in the next iteration and then decide about the future of the script (opt. 1 vs 3).

**Comment by jsoriano** [comment]
Script is deprecated now (since https://github.com/elastic/integrations/pull/3652), and we will eventually remove it.
