### ISSUE TITLE
Discuss: where should we keep "update-package-storage" script

### ISSUE THREAD

**Issue by mtojek** [elastic/elastic-package#153]
The tool should be migrated away from the integrations repository, not necessarily be part of any specific tool.

Consider moving it to `integrations-extras` or `elastic-package`.

It's related to the final design of the package registry.

**Comment by mtojek** [comment]
We can also consider changing the release logic. As we store multiple packages in a single repository, a single broken package shouldn't block the release cycle of others.

**Comment by mtojek** [comment]
@ycombinator It's a similar thread to https://github.com/elastic/elastic-package/issues/152 , but we can improve scripts to be non-blocking (see the post above) and put it under `.ci`.

**Comment by ycombinator** [comment]
For this one I feel like https://github.com/elastic/elastic-package/issues/21 is the right replacement. By implementing it, we allow any package from any source (not just packages under https://github.com/elastic/integrations) to be published to the registry (i.e. `package-storage` today but that could change with the registry redesign). Then we can adjust the automation in the https://github.com/elastic/integrations repo to call `elastic-package publish` instead of `update-package-storage`.

**Comment by mtojek** [comment]
I totally forgot about https://github.com/elastic/elastic-package/issues/21 . Thanks! This is a great replacement for this issue. I will close this issue in favor of the other one.
