### ISSUE TITLE
Add SonarQube generic-test-data format support for code coverage report.

### ISSUE THREAD

**Issue by sharbuz** [elastic/elastic-package#1595]
Currently, code coverage reports are analyzed in the [Jenkins Cobertura plugin](https://plugins.jenkins.io/cobertura/).
Jenkins will be decommissioned soon and it was decided to use Elastic SonarQube for code coverage report analysis.
Elastic SonarQube can't analyze the reports made by the elastic-package tool because the SonarQube Java Cobertura coverage reports [haven't been supported](https://community.sonarsource.com/t/cobertura-generated-coverage-xml-file-is-not-loading-so-sonar-qube-shows-0-0-coverage/42654/5) and it requires using [generic-test-data format](https://docs.sonarsource.com/sonarqube/latest/analyzing-source-code/test-coverage/generic-test-data/).
The elastic-package tool has to be updated to support the new format of the reports.
After Jenkins decommissions the support of the Java Cobertura coverage reports should be decommissioned.

Pipelines from [integrations repository](https://github.com/elastic/integrations) should be updated to enable these coverage reports too.

Example from integrations repository:
https://github.com/elastic/integrations/pull/3671#issuecomment-1179131728

Current docs about coverage: https://github.com/elastic/integrations/blob/6c808f49d404ac9f29451297a3a991e6026e7fe0/docs/testing_and_validation.md#review-test-coverage

**Comment by mrodm** [comment]
In a build triggered from this PR https://github.com/elastic/integrations/pull/8464
there was an error related that the files were not found in the working copy ([build link](https://buildkite.com/elastic/integrations/builds/7289#018c59c6-d02d-42b7-91a4-54e3d32fdf3b/106-284)):

```
INFO: Sensor Cobertura Sensor for Python coverage [python]
INFO: Python test coverage
INFO: Parsing report '/buildkite/builds/bk-agent-prod-k8s-1702313828449526795/elastic/integrations/build/test-coverage/coverage-report/coverage.xml'
ERROR: Cannot resolve the file path 'elastic_package_registry/metrics' of the coverage report, the file does not exist in all 'source'.
```
Example of XML generated.

```xml
<coverage line-rate="0" branch-rate="0" version="" timestamp="1702313791649554954" lines-covered="0"
    lines-valid="0" branches-covered="0" branches-valid="0" complexity="0">
    <sources />
    <packages>
        <package name="elastic_package_registry" line-rate="0" branch-rate="0" complexity="0">
            <classes>
                <class name="asset" filename="elastic_package_registry/metrics" line-rate="0"
                    branch-rate="0" complexity="0">
                    <methods>
                        <method name="OK" signature="" line-rate="0" branch-rate="0" complexity="0"
                            hits="0">
                            <lines>
                                <line number="1" hits="1" />
                            </lines>
                        </method>
                    </methods>
                    <lines />
                </class>
            </classes>
        </package>
    </packages>
</coverage>
```


Tried to update the filename in the coverage XML file here:
https://github.com/elastic/elastic-package/pull/1612

Example of the XML report with these changes:
```xml
<coverage line-rate="0" branch-rate="0" version="" timestamp="1703251376805682576" lines-covered="0"
    lines-valid="0" branches-covered="0" branches-valid="0" complexity="0">
    <sources />
    <packages>
        <package name="elastic_package_registry" line-rate="0" branch-rate="0" complexity="0">
            <classes>
                <class name="pipeline"
                    filename="packages/elastic_package_registry/data_stream/metrics/manifest.yml"
                    line-rate="0" branch-rate="0" complexity="0">
                    <methods>
                        <method name="OK" signature="" line-rate="0" branch-rate="0" complexity="0"
                            hits="0">
                            <lines>
                                <line number="1" hits="1" />
                            </lines>
                        </method>
                    </methods>
                    <lines />
                </class>
            </classes>
        </package>
    </packages>
</coverage>
```

Tested in this PR https://github.com/elastic/integrations/pull/8787 . Currently, it looks like the XML file is parsed, but there is no coverage report yet ([build link](https://buildkite.com/elastic/integrations/builds/7727#018c91a7-2753-4e98-9e0d-1e99a6f60f3d/110-285)).

```
INFO: Sensor Python Sensor [python] (done) | time=3197ms
INFO: Sensor Cobertura Sensor for Python coverage [python]
INFO: Python test coverage
INFO: Parsing report '/buildkite/builds/bk-agent-prod-k8s-1703251418207532017/elastic/integrations/build/test-coverage/coverage-report/coverage.xml'
INFO: Sensor Cobertura Sensor for Python coverage [python] (done) | time=959ms
```

**Comment by mrodm** [comment]
Tried without errors and updating the pipeline coverage report too: 
https://github.com/elastic/elastic-package/pull/1612/commits/40b4507d7e91ee311234025a5cd415bfdf95d82a

Updated in the integrations PR, and this is the build: https://buildkite.com/elastic/integrations/builds/7728

**Comment by mrodm** [comment]
After talking to @jsoriano offline:
- Test with generic data test cases (to remove python hack in sonar.properties).
- Create a new flag to generate those generic XML files and keep the cobertura coverage report in another flag.
- Keep the workaround for the asset/system/static tests (assuming one different line per test type)

**Comment by mrodm** [comment]
SonarQube requires that the files defined in the XML reports exist in the repository. Tested for Sensor Python Cobertura and Generic test data.

For instance, for a generic test data containing a non-existing file, that file was ignored:
```
INFO: Imported coverage data for 2 files
INFO: Coverage data ignored for 1 unknown files, including:
packages/elastic_package_registry/data_stream/metrics/other.yml
```

This requires that for asset, system, static and pipeline (if no ingest pipeline is defined) tests, the file defined in the XML should exist in the repository and refer to an existing line of that file too.

Example of XML (this is not a real coverage report from `elastic_package_registry`):
```xml
<coverage version="1">
  <file path="packages/elastic_package_registry/data_stream/metrics/manifest.yml">
    <lineToCover lineNumber="1" covered="true"/>
    <lineToCover lineNumber="2" covered="true"/>
    <lineToCover lineNumber="3" covered="true"/>
    <lineToCover lineNumber="4" covered="false"/>
  </file>
  <file path="packages/elastic_package_registry/data_stream/metrics/elasticsearch/ingest_pipeline/default.yml">
    <lineToCover lineNumber="4" covered="true"/>
    <lineToCover lineNumber="5" covered="true"/>
    <lineToCover lineNumber="6" covered="true"/>
    <lineToCover lineNumber="7" covered="true"/>
    <lineToCover lineNumber="8" covered="true"/>
    <lineToCover lineNumber="9" covered="true"/>
    <lineToCover lineNumber="10" covered="true"/>
    <lineToCover lineNumber="11" covered="true"/>
  </file>
</coverage>
```

**Comment by mrodm** [comment]
Created these issues with bugs found while working on this task:
- https://github.com/elastic/elastic-package/issues/1623
- https://github.com/elastic/elastic-package/issues/1624

**Comment by mrodm** [comment]
Apart from adding in `elastic-package` this new format, it is needed to enable these coverage reports in the integrations repository. This has been tested in this PR https://github.com/elastic/integrations/pull/8787

It looks like if some XML is not generated in the main branch, it could be removed from the coverage report in SonarQube when performing the analysis and uploading the report to SonarQube. **Just tested in the context of a Pull Request and not 100% sure about its behaviour for builds/analysis running in main branch.**

Currently, not all packages are tested every time a PR is merged into main for integrations repository. The number of packages to be tested in main depends on the status of the previous PRs merged (success or failure) to see how many packages have been updated since the latest failure and test all those packages. This repository is different on how a "regular" repository of a service code for instance in Java or Golang works, since in those repositories all the tests would be running and all the coverage would be calculated in every build.

Having considered this, I can think of these different options to enable coverage reports/analysis:
1. enable it directly in main branch (main pipeline) for all builds
    - this involves PR and every build triggered as a consequence of a push to main branch (even builds triggered by the schedule daily job)
2. enable it in PRs and in the [schedule-daily job](https://github.com/elastic/integrations/blob/3840a7fa5852ae57ce16179117be47c613f3a2cd/.buildkite/pipeline.schedule-daily.yml) for both local stacks (serverless is not running system tests)
    - this would avoid running coverage for builds triggered as a consequence of a merge into main
3. enable this in PRs and in the [schedule-daily job](https://github.com/elastic/integrations/blob/3840a7fa5852ae57ce16179117be47c613f3a2cd/.buildkite/pipeline.schedule-daily.yml) for just one version of Elastic stack (e.g. 8.X)
    - this would avoid running coverage for builds triggered as a consequence of a merge into main
4. any other option to add here ? 

One option to try to run always the same number tests would be enable this coverage step in the [schedule-daily job](https://github.com/elastic/integrations/blob/3840a7fa5852ae57ce16179117be47c613f3a2cd/.buildkite/pipeline.schedule-daily.yml) just for one local stack version (e.g. 8.X version). Even in this case, there could also be some packages that could not be tested due to some failures booting up the Elastic stack, but most of the times should be running all the tests for all those packages.

Should we go for enabling directly in main for all builds and check/confirm how it behaves or maybe the third one mentioned above ? @elastic/ecosystem

**Comment by jlind23** [comment]
@mrodm I do think option 3 is the best option and will allow us on the long run to make code coverage a gating criteria.

**Comment by jsoriano** [comment]
+1 to option 3

**Comment by mrodm** [comment]
Pending a new elastic-package version  including this PR at least 
https://github.com/elastic/elastic-package/pull/1612 to continue working on adding the required coverage reports (https://github.com/elastic/integrations/pull/8787/).

**Comment by mrodm** [comment]
As checked here https://buildkite.com/elastic/integrations/builds/8403#_, if there are `routing_rules.yml` defined in the package, `elastic-package` automatically adds `reroute` processors to the ingest pipeline (even if they are not defined in the ingest pipeline file).

Those processors that are added cause that the coverage reports (e.g. line numbers) do not correlate with the ingest pipeline files and the sonar scanner CLI reports that as a failure.

Created this PR as a way of removing these processors from the coverage reports:
https://github.com/elastic/elastic-package/pull/1647

Processors stats should remain the same, since it has been added a new method for this purpose.
