### ISSUE TITLE
Add more guidance for undefined environment variable ELASTIC_PACKAGE_ELASTICSEARCH_HOST

### ISSUE THREAD

**Issue by mtojek** [elastic/elastic-package#192]
User story:

A developer may forget to boot up the local cluster or evaluate "stack shellinit". Currently the tool fails with the following message:

```
Error: fetching Elasticsearch client instance failed: undefined environment variable: ELASTIC_PACKAGE_ELASTICSEARCH_HOST 
```

We can consider different options:
1. Leave as is.
2. Add more guidance: suggest to use "shellinit".
3. Use environment defaults.
4. Try to connect to the localhost and in case of failure, output proper guidance.

/cc @exekias @ycombinator @ChrsMark

**Comment by exekias** [comment]
Thanks for opening!

I think at the very least we could output some instructions to run `shellinit` after `stack up` is done. I wonder what's the most common case. If most users are just running this in docker on the localhost, perhaps option 4 makes sense? That would improve the default experience, while still work for more advanced use cases.

**Comment by ycombinator** [comment]
I think we should do two things:

- point 2 above: that is, when any `elastic-package` command that depends on environment variables is executed, we should check as early as practical in that command's execution if the necessary environment variables are set; if not, we show the appropriate error message and suggest that the user runs `elastic-package shellinit` if they are started the stack with `elastic-package stack up`, otherwise they should simply set the required variables to appropriate values.

- at the end of `elastic-package stack up`, suggest that the user runs `elastic-package shellinit` to use the stack with other `elastic-package` commands.

**Comment by mtojek** [comment]
I'm going with this feature.
