### ISSUE TITLE
In case of emergency - select Docker image references in the Elastic stack

### ISSUE THREAD

**Issue by mtojek** [elastic/elastic-package#271]
There was [another issue](https://github.com/elastic/beats/issues/24310) introduced to Elastic Agent, which caused problems with booting up the Elastic stack (unhealthy container with elastic-agent).

The goal of this issue is to figure out a workaround to quickly specify Docker image references.

**Comment by mtojek** [comment]
Let's discuss multiple options:

1. Global environment variables

If these values are set, they will override default values for Docker Compose template.

```
ELASTIC_PACKAGE_STACK_ELASTICSEARCH_IMAGE=docker.elastic.co/elasticsearch/elasticsearch:7.13.0-SNAPSHOT
ELASTIC_PACKAGE_STACK_KIBANA_IMAGE=docker.elastic.co/kibana/kibana:7.13.0-SNAPSHOT
ELASTIC_PACKAGE_STACK_ELASTIC_AGENT_IMAGE=docker.elastic.co/beats/elastic-agent@sha256:75c9fbf835a7d24166bceb82f28f4c6c5d00048ba9f0a25b945818e4cf2bba69
```

(I suggested `image` instead of version because of format different between snapshot/release and sha256)

2. Local file with key-values.

A local config file passed as CLI option that contains additional settings. Something similar to https://github.com/elastic/elastic-package/issues/179 . I'm not sure if I'm convinced to this form - can't figure out the best place in the filesystem to keep it.

3. Additional CLI options

so it would be:

```
elastic-package stack up --elasticsearch-image-ref "docker.elastic.co/elasticsearch/elasticsearch:7.13.0-SNAPSHOT" --elastic-agent-image-ref "docker.elastic.co/beats/elastic-agent@sha256:75c9fbf835a7d24166bceb82f28f4c6c5d00048ba9f0a25b945818e4cf2bba69"
```

---

With options 1 and 3 we may control it without push&deployment of new revisions of elastic-package. Just have to open a PR to integrations to temporarily modify the Jenkinsfile. 

---

4. Tiny `versions` file kept in elastic-package's repository

The file will be available online (master branch) and the elastic-package will have to fetch it if not present locally or `elastic-package update` has been triggered. Later on this file will be used to fetch latest/safest references to images (either `7.13.0-SNAPSHOT` or `sha256@....`.

cc @ycombinator

**Comment by ycombinator** [comment]
I am personally a fan of option 2 but with a slight modification, inspired by files like [`.nvmrc`](https://medium.com/@faith__ngetich/locking-down-a-project-to-a-specific-node-version-using-nvmrc-and-or-engines-e5fd19144245) and [`kibana.dev.yml`](https://www.elastic.co/guide/en/kibana/master/running-kibana-advanced.html#customize-kibana-yml).

When `elastic-package` is (re)installed and the `~/.elastic-package` folder is created, a default config file, say `config.yml`, is also installed under it. `elastic-package` reads values from this file to decide things like image versions, etc. Users should not be touching this file.

Additionally, we can create and commit a `.elastic-package/config.yml` to the integrations repo. This file can contain any repo-level configuration that will override the defaults in `~/.elastic-package/config.yml`.

Finally, individual developers can create (but never commit — enforced via `.gitignore`) a `.elastic-package/config.dev.yml` file. This file contains developer-specific configuration that will override the values in `.elastic-package/config.yml`.

---

I'm not in favor of option 1 because the number of environment variables needed for using `elastic-package` are starting to grow. Also with environment variables it's not very ergonomic to express configuration setting hierarchies or groupings either.

For similar reasons, I'm also not in favor of option 3.

As for option 4, I think the above tweaks to your option 2 would cover it?

WDYT?

**Comment by mtojek** [comment]
> Additionally, we can create and commit a .elastic-package/config.yml to the integrations repo. This file can contain any repo-level configuration that will override the defaults in ~/.elastic-package/config.yml.
Finally, individual developers can create (but never commit — enforced via .gitignore) a .elastic-package/config.dev.yml file. This file contains developer-specific configuration that will override the values in .elastic-package/config.yml.

Actually it might be a good choice. I admit I wanted to have a global place to select the best (stable) version of the stack, but your idea seem to be more flexible.

We can go with option 2 and later on decide if we want to tweak it or not. The only thing we need to remember is the requirement to push special commits to integrations and elastic-package in case of emergency (instead of a single place according to the option 4)

**Comment by jsoriano** [comment]
Are there plans to use fixed versions not only in case of emergency, but always? I understand that we are now in a phase of heavy development and using the snapshots may be helpful to detect issues earlier, but longer term this is creates frictions and unexpected interruptions on packages development.
The option we chose here should have this in mind, that this hopefully will be the rule and not the exception.

**Comment by mtojek** [comment]
I suppose it depends on the failure rate. We started with 8.0.0-SNAPSHOT, but that version was not really stable for us, so we switched to the latest 7.x-SNAPSHOT and that revision behaved well for longer time (until last week).

There shouldn't be any technical difficulties to depend on fixed version unless we get outdated really quickly and switching stack versions becomes a problem.

**Comment by ycombinator** [comment]
Under the 3-tier configuration model (`elastic-package` <- repo <- local), I was thinking the permanent version is the one that should come from `elastic-package`. We should only set a the version in the repo in case of an emergency; once the emergency is gone, we should remove the version from the repo config so we fallback to the permanent version in `elastic-package`. The local tier is for any local experimentation.

Also, note that this model is not just for stack versions but also other configuration settings (see #179).

**Comment by mtojek** [comment]
@ycombinator do you think we can improve something in this are?

**Comment by ycombinator** [comment]
I think we can close this issue. https://github.com/elastic/elastic-package/pull/275 resolves it IMO.
