### ISSUE TITLE
Allow for default *-config.yml on pipeline tests

### ISSUE THREAD

**Issue by P1llus** [elastic/elastic-package#289]
There is plenty of pipelines that has a very large amount of logfiles that they want to test with, one example is cisco and panw.

The current situation is that for pipeline tests it seems that it will only allow for configurations based on a specific config name pattern:
`LOGFILENAME-config.yml`.

Which means that we end up with the same config copied 5-10 times.

It would be great when during pipeline tests, that if it cannot find a config file for the specific logfile, it would default to trying to find something like `test-default-config.yml`, that way we could remove most of the testing config files we have.

**Comment by mtojek** [comment]
Thanks for filing the issue, it's an interesting side effect. We may actually introduce a default test config which can be picked up by all pipeline test cases without specific config files. @ycombinator any opinions here?

**Comment by P1llus** [comment]
While it might introduce more work, it would be nice to have a hierarchy of configurations.

Global config (with config items like adding `event.ingested` to dynamic fields, which is needed pretty much everywhere)
Package wide config, with `test-default-config.yml`.
Data-stream config, with `LOGFILENAME-config.yml` (which we have already).

**Comment by ycombinator** [comment]
I'm generally in favor of this idea but I'd only start by implementing as much of it as we need at the moment with room to grow in the future. I'd also clarify exactly the hierarchy of config inheritance, especially since we have different _types_ of tests (pipeline, system, etc.).

@P1llus correct me if I'm wrong but sounds like what you are looking for _at the moment_ is a single config that defines common options for multiple pipeline test case files in a data stream? So something like this:

```
<package root>
  data_stream/
    foo/
      _dev/test/pipeline/
        LOGFILENAME_1-config.yml
        LOGFILENAME_2-config.yml
        ...
       common-config.yml    // ignore the exact naming, just want to illustrate the idea
    bar/
      _dev/test/pipeline/
        LOGFILENAME_1-config.yml
        LOGFILENAME_2-config.yml
        ...
       common-config.yml    // ignore the exact naming, just want to illustrate the idea
```

So, in the above example, settings from `<package root>/data_stream/foo/_dev/test/pipeline/common-config.yml` would be inherited by all its sibling `LOGFILENAME_*-config.yml` files. Similarly, settings from `<package root>/data_stream/bar/_dev/test/pipeline/common-config.yml` would be inherited by all its sibling `LOGFILENAME_*-config.yml`, correct?

I understand the idea of extending this hierarchy even higher but just want to check if the above proposal would get you what you need at the moment or if there's more commonality desired?

**Comment by P1llus** [comment]
@ycombinator that is indeed correct, what is more important is that this common.yml should also work when a more specific file does not exist at all, most usecases will have the same settings for all test files.

**Comment by ycombinator** [comment]
Cool, thanks for confirming @P1llus. 

> what is more important is that this common.yml should also work when a more specific file does not exist at all

++, we're on the same page about this.

So I'm +1 to going ahead with this feature but only keeping the inheritance hierarchy limited to what is illustrated in https://github.com/elastic/elastic-package/issues/289#issuecomment-799487305 **for the initial implementation**. We can always extend it to go even higher when we have that use case.
