### ISSUE TITLE
Push custom package to a non-local kibana

### ISSUE THREAD

**Issue by matschaffer** [elastic/elastic-package#357]
The install helper is very interesting for working against the local kibana, but it'd be good to have some answer for pushing the package up to a standing kibana without having to do a full release.

The case I'm thinking about here is a developer working on a dashboard for their own service.

They add some metrics to their service (maybe a new prometheus counter), add it to a dashboard in their staging env, then want to get that update into their package and pushed to a production environment to see if the visualization makes sense against live data.

**Comment by mrodm** [comment]
Since version [`v0.76.0`](https://github.com/elastic/elastic-package/releases/tag/v0.76.0) (PR https://github.com/elastic/elastic-package/pull/1163), `elastic-package install` command was updated to use the Kibana API that allows to install a zip package directly, so they can be installed from source.
