### ISSUE TITLE
Extend elastic-package install command

### ISSUE THREAD

**Issue by jlind23** [elastic/elastic-package#646]
`elastic-package install` currently installs package that ARE published in the registry.

The aim of this issue to extend the install command in order to specify integrations that may be available only locally.
It will developer experience as they may need to deploy multiple integrations that are only available on their machine for example.

**Comment by mtojek** [comment]
It seems to be related to the original idea for the `sync` command: https://github.com/elastic/elastic-package/issues/9. It will provide a similar value.

**Comment by mrodm** [comment]
Since version [`v0.76.0`](https://github.com/elastic/elastic-package/releases/tag/v0.76.0) (PR https://github.com/elastic/elastic-package/pull/1163), `elastic-package install` command was updated to use the Kibana API that allows to install a zip file directly, so packages can be installed from source.
