### ISSUE TITLE
Add subcommand for stack status

### ISSUE THREAD

**Issue by jsoriano** [elastic/elastic-package#836]
Add subcommand that prints the status of the stack managed by `elastic-package stack`, including the version started.

This subcommand could be `elastic-package stack status`.

**Comment by efd6** [comment]
It would be good if this also printed the version used when printing test outcomes (particularly for failures).

**Comment by mrodm** [comment]
> It would be good if this also printed the version used when printing test outcomes (particularly for failures).

Adding that information in the test outcomes looks like is going to be helpful in case of failures. A new issue has been created in order to add it as part of the test output https://github.com/elastic/elastic-package/issues/922.

Currently, we're working to create the new command `elastic-package status stack` so it can be checked independently from tests to get the services running as well as their version and status (https://github.com/elastic/elastic-package/pull/917).
