### ISSUE TITLE
Add fields to integrations by default

### ISSUE THREAD

**Issue by ishleenk17** [elastic/elastic-package#949]
As part of elastic package, it would be good to have the below fields in the default template of elastic package create, so that every integration inherits these. 

1. Tags
2. Processors
3. ignore-older

These fields can be optional for the users. 

The above would provide us unanimity across integrations and more flexibility to users. 

cc: @ruflin

**Comment by mtojek** [comment]
pinging @elastic/ecosystem and @mukeshelastic for prioritization

**Comment by ruflin** [comment]
One of the options is to add these to each package. The other one is to have it as a feature of Fleet like `data_stream.dataset` value. 

I think `ignore_older` falls under its own category as it only applies to the logs input.

**Comment by jsoriano** [comment]
I agree that they would offer a lot of flexibility to users, but I think that there are already other efforts intended to cover these areas.

For example [custom processing](https://github.com/elastic/kibana/issues/133740) is being added to Fleet. Having it in Fleet makes it available for all packages without adding anything. Any improvement in this area will benefit all packages, including existing ones.
When adding custom processing you will end up needing custom mappings or other features, that is better to solve in a single place.
Adding processors in packages would offer another way of doing custom processing, but limited, and not aligned with other efforts. Also, this processing would happen on the agent side, when the current tendency is to bring processing to the ingest nodes.

Tags would be covered by any solution intended for custom processing. If you can do custom processing, you can add tags.
If we want to have specific settings to add tags instead of using generic custom processing, I think that this should also be implemented in Fleet.

Regarding `ignore_older`. This is a specific setting of an specific input. There are many other settings and many other inputs, it is not possible to expose them all in all packages. For this a better solution would be [input packages](https://github.com/elastic/package-spec/issues/361), another effort already in progress, that will allow to expose input-specific settings, and make them available for its use along with other packages.

**Comment by ruflin** [comment]
We need to split up a few things here:

* global processing: should be done in ingest pipelines
* local processing where local knowledge is needed: things like looking up host info, dropping filtering events

I don't think the custom processing covers the local case. For tags, it is also a bit different. Assuming we have multiple policies shipping system metrics. All metrics go to the same data stream, but for the "east coast" policy a tag should be added to each event and one for the "west coast" policy. This can't be done globally AFAIK.

**Comment by jsoriano** [comment]
Good points on global vs. local processing. I still wonder if, given that we want this in all packages (or all packages of certain kinds), the config for local processing should be also managed by Fleet. This would allow to change the implementation without needing to change all packages.
Imagine for example looking up host info (or any other local info), it could be based now on local processors, but there could be also an implementation based on the enrichment processor that could allow to centralize the collection of this data in one agent, instead of needing implementations and error-prone yaml configurations on each collector of this agent. Something like this has been discussed in some [other](https://github.com/elastic/package-spec/issues/37) [places](https://github.com/elastic/package-spec/issues/292).

It is true that we are probably far from having anything based on enrichment processor, but still, I think it'd be preferred if things wanted the same in all packages of a kind are managed by Fleet. For consistency and to reduce the number of things package developers need to take into account.

> For tags, it is also a bit different. Assuming we have multiple policies shipping system metrics. All metrics go to the same data stream, but for the "east coast" policy a tag should be added to each event and one for the "west coast" policy. This can't be done globally AFAIK.

Another good point, but this sounds to me more like a limitation of the current approach for custom processing. As a user I would expect to be able to add different custom processing per policy, the data stream is more an implementation detail.

My main point is that requiring to add something to all packages to have some desired functionality sounds like a source of problems: there can be inconsistencies between packages and it increases complexity (and error-proneness) of package development.

**Comment by ishleenk17** [comment]
**Processors**:
I think from the above discussions we agree that local processing is required as well. 
The next point for discussion being if we have to do it at package or fleet level. 
`To avoid inconsistencies across packages, I think it would be a good idea to have these implemented at Fleet level along with custom processing. `

**Tags:** 
Is there an agreement that we would be having custom processing at policy level ? That would help us avoid usage of tags. 

**ignore_older:** 
@jsoriano : You mentioned that input packages would take care of these. Would this be a default setting available in the appropriate input package or a customer using these input packages for their service would have to add these in config ?

Pinging @elastic/obs-service-integrations

**Comment by jsoriano** [comment]
> @jsoriano : You mentioned that input packages would take care of these. Would this be a default setting available in the appropriate input package or a customer using these input packages for their service would have to add these in config ?

The log input package would have this option, yes. Ideally these inputs could use the pipelines of other packages, providing a similar functionality to the definition of custom inputs in Filebeat modules configuration.
The UX for this is still under discussion: https://github.com/elastic/kibana/issues/133296.

**Comment by ishleenk17** [comment]
@jsoriano : Is there any ticket for custom processing at policy level ?
@ruflin  Also, I suppose we should proceed with having processors implementation at fleet level. We can check further on this with Fleet team.

**Comment by ruflin** [comment]
> The log input package would have this option, yes.

This triggered a more fundamental idea on my end. What if Fleet becomes knowledge about certain "core" inputs like logfile? Instead of each package having to figure out what the necessary fields are for using the logs input instead Fleet would have some basic knowledge. Or a package would inherit it from the log input package? This could be an extension of the input package development https://github.com/elastic/kibana/issues/133296 @kpollich It makes it even more clear that any non input package is basically an extension of an input package (or multiple of them).

**Comment by jsoriano** [comment]
> Is there any ticket for custom processing at policy level ?

Not that I know, I'd say this is a new idea that has appeared here. Pinging @kpollich for his opinion here.

> What if Fleet becomes knowledge about certain "core" inputs like logfile? Instead of each package having to figure out what the necessary fields are for using the logs input instead Fleet would have some basic knowledge. Or a package would inherit it from the log input package?

Yes, I think we should go in the direction of including this information in the specific input packages and not on every package. Fleet would also get the knowledge about these options from the input packages, this knowledge shouldn't be hardcoded in Fleet.

**Comment by ishleenk17** [comment]
There are couple of SDH's and other public issues raised for having processors for integrations to have consistency across integrations:
https://github.com/elastic/sdh-beats/issues/2429
https://github.com/elastic/sdh-beats/issues/2433
https://github.com/elastic/integrations/issues/3431


> Also, I suppose we should proceed with having processors implementation at fleet level. We can check further on this with Fleet team.

@kpollich: Could you please let us know about any dependencies if these processors are required to be implemented at Fleet Level.

**Comment by kpollich** [comment]
> Is there any ticket for custom processing at policy level ?

I believe this is the issue we're looking for here: https://github.com/elastic/kibana/issues/122892

> Could you please let us know about any dependencies if these processors are required to be implemented at Fleet Level.

I don't think we have any real blockers on our end, as we already support custom processors for the Custom Logs integration. We'd just need to do some definition/architecture around how we'll expand that support to all integrations.

> What if Fleet becomes knowledge about certain "core" inputs like logfile? Instead of each package having to figure out what the necessary fields are for using the logs input instead Fleet would have some basic knowledge. Or a package would inherit it from the log input package?
> 
> Yes, I think we should go in the direction of including this information in the specific input packages and not on every package. Fleet would also get the knowledge about these options from the input packages, this knowledge shouldn't be hardcoded in Fleet.

I like these thoughts, but I wonder about the feasibility of "cross package lookups". e.g. I have the `nginx` package which "extends" the `logs` input package. The `logs` input package defines support for custom processors, `ignore_older`, etc. Does Fleet need to go fetch that input package (or otherwise have some internal reference to it) in order to resolve those fields/options? Right now a single package is its own source of truth. If we have this notion of extending "base packages" we break that assumption which feels incorrect to me.

If this isn't the case, and a single package manifest still contains all the package data Fleet needs to operate, then the "base package" notion is not a Fleet concern and instead should be handled by the `elastic-package` CLI when bootstrapping a package. e.g. we can create an `nginx` package that extends the `logfile` base package and is pre-populated with the extended fields.

**Comment by ruflin** [comment]
> I like these thoughts, but I wonder about the feasibility of "cross package lookups". e.g. I have the nginx package which "extends" the logs input package. The logs input package defines support for custom processors, ignore_older, etc. Does Fleet need to go fetch that input package (or otherwise have some internal reference to it) in order to resolve those fields/options? Right now a single package is its own source of truth. If we have this notion of extending "base packages" we break that assumption which feels incorrect to me.

> If this isn't the case, and a single package manifest still contains all the package data Fleet needs to operate, then the "base package" notion is not a Fleet concern and instead should be handled by the elastic-package CLI when bootstrapping a package. e.g. we can create an nginx package that extends the logs base package and is pre-populated with the extended fields.

All very good thoughts. Do not derail the initial conversation of the Github issue, should we take this to a new issue?

**Comment by ishleenk17** [comment]
> I don't think we have any real blockers on our end, as we already support custom processors for the Custom Logs integration. We'd just need to do some definition/architecture around how we'll expand that support to all integrations.

@kpollich I have raised a Github ticket for the same. https://github.com/elastic/kibana/issues/139900. 
Please let me know if this can be picked as part of next iteration. There have been multiple SDH requests for the same. 


> I believe this is the issue we're looking for here: [elastic/kibana#122892](https://github.com/elastic/kibana/issues/122892)

Also, regarding https://github.com/elastic/kibana/issues/122892, for custom processing at policy level. 
Could you please share the completion schedule for the same.

**Comment by kpollich** [comment]
cc @jen-huang @nimarezainia - See above for requested work in 8.6

**Comment by ishleenk17** [comment]
If we implement processors in Fleet UI, what would be the behaviour of the integrations that already have a processor yaml box and are brought up on the new UI. 
@ruflin @kpollich : Thoughts ?

**Comment by ishleenk17** [comment]
Gisting out AI's here:

1. Processors: This is which we expect to be added through Fleet: 
           https://github.com/elastic/kibana/issues/139900.
> cc @jen-huang @nimarezainia - See above for requested work in 8.6

@jen-huang @nimarezainia : Could you please incorporate this in 8.6 planning. It would be a great addition for integrations from Fleet. 

2. Tags: If the processing is at policy level, having tags can be avoided. 
@kpollich, @jen-huang @nimarezainia  : https://github.com/elastic/kibana/issues/122892 Is this planned for 8.6 ?

3. ignore_older: For now if there is an urgent ask for this, we will add it to specific integration. Once input package are implemented, we expect these to be part of the input

**Comment by ruflin** [comment]
> If we implement processors in Fleet UI, what would be the behaviour of the integrations that already have a processor yaml box and are brought up on the new UI.

I expect that we have quite a few scenarios in the future where certain configs become obsolete because these will be removed eventually or were taken over by another config. In an ideal scenario we can just migrate users but I guess this is not the case here. One idea would be to mark this fields as deprecated. For any user where the field already contains content, it still shows up and these users have to migrate over to the new feature manually. For any other user, it does not show up.

**Comment by gizas** [comment]
Team, @ishleenk17 and @kpollich we have started discussion for processors but same scenario (and even with more importance for us) is to expose `conditions` as well : See relevant issues here: 
- Selective monitoring of workloads through user provided conditions on fleet  elastic-agent#707
- https://github.com/elastic/integrations/issues/1867#issuecomment-1255869326

**Comment by ChrsMark** [comment]
> Team, @ishleenk17 and @kpollich we have started discussion for processors but same scenario (and even with more importance for us) is to expose `conditions` as well : See relevant issues here:
> 
> * [Selective monitoring of workloads through user provided conditions on fleet  elastic-agent#707](https://github.com/elastic/elastic-agent/issues/707)
> * [Investigate and capture design for autodiscovery conditions in integrations UI integrations#1867 (comment)](https://github.com/elastic/integrations/issues/1867#issuecomment-1255869326)
> 
> What do you think?

++++

Having the option to define a `condition`, of any kind, for any integration at the time of adding the integration through the Fleet UI is super important from my perspective.

See more information at https://www.elastic.co/guide/en/fleet/master/dynamic-input-configuration.html.

The thing here is that even we have such a powerful feature implemented in Agent's core we can only use in standalone Agent or hardcode it within a package definition. This is exactly the same situation with `processors` I think.

@ruflin @ishleenk17 what are your thoughts here? Happy to provide more information or share my input more extensively :).

**Comment by ishleenk17** [comment]
> The thing here is that even if we have such a powerful feature implemented in Agent's core we can only use in standalone Agent or hardcode it within a package definition. This is exactly the same situation with `processors` I think.

@gizas @ChrsMark : If I understand correctly, just like we take hosts, period etc as inputs from users, the requirement is to take conditions also as input from user. But is this requirement only for K8s related integrations ?

This looks similar to our ask here, having processors and tags as inputs by default for all the integrations. 
`If we can generalize all of this and fleet is able to cater to these requirements through a single box (be it text, yaml, etc), we can handle any such requirements for future as well `instead of adding a separate input box for any new input to be taken from user. 
@kpollich : please share your thoughts on this.

**Comment by ChrsMark** [comment]
> > The thing here is that even if we have such a powerful feature implemented in Agent's core we can only use in standalone Agent or hardcode it within a package definition. This is exactly the same situation with `processors` I think.
> 
> @gizas @ChrsMark : If I understand correctly, just like we take hosts, period etc as inputs from users, the requirement is to take conditions also as input from user. But is this requirement only for K8s related integrations ?
> 
The requirement is exactly this! However it's not only for Kubernetes related integrations but for all. Also keep in mind that the conditions' feature is not k8s specific, its generic and can be related to any of the Elastic Agent's provider, like docker, host, local etc.

> This looks similar to our ask here, having processors and tags as inputs by default for all the integrations. `If we can generalize all of this and fleet is able to cater to these requirements through a single box (be it text, yaml, etc), we can handle any such requirements for future as well `instead of adding a separate input box for any new input to be taken from user. 

Based on the above clarification, the need for having `condition` as a generic user input is something that we need in general and not only in k8s or any other specific integration/environment.

I would think of this user input similarly to what we have for `namespace` or `description:
![Screenshot from 2022-09-26 13-17-59](https://user-images.githubusercontent.com/11754898/192252760-400f4760-e517-4733-957f-3c8732c749ca.png)

**Comment by ishleenk17** [comment]
> I would think of this user input similarly to what we have for `namespace` or `description:

So this input is required at global level of integration and not at datastream level ?
Processors/tags requirement is at datastream level.

**Comment by ChrsMark** [comment]
> > I would think of this user input similarly to what we have for `namespace` or `description:
> 
> So this input is required at global level of integration and not at datastream level ? Processors/tags requirement is at datastream level.

As far as I know, `conditions` are supported on both levels...so you can define one on integration level and on data_stream level. Here for simplicity we can decide to have it on data_stream level (if it's not a bad UX decision that would make users, copy pasting the same condition....).

**Comment by gizas** [comment]
>So this input is required at global level of integration and not at datastream level ?
Also Processor's can be added on global integration level and on datastream level is not it? Have we discussed there the approach? 

Of course the decision to inlcude it only on datastream level makes implementation I guess simpler now, but for UX I would not like to put same block of code in many datastreams. I guess needs to go in both levels (although see it coming in future sdhs)

**Comment by ishleenk17** [comment]
@gizas : For processors, the processor required for one datastream might differ from the one required for other datastream.
Hence having only global one won't work.

The condition input is going to be same for all datastreams ? If yes, then of course global level makes sense.

**Comment by ChrsMark** [comment]
Conditions might be needed on integration level and/or data_stream level. 

An example of condition that applies to more than one data_streams and hence it's defined on input/integration level: https://github.com/elastic/elastic-agent/blob/main/deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml#L32 

An example of condition defined on data_stream level: https://github.com/elastic/elastic-agent/blob/main/deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml#L515

Hence, we can actually make it possible to define conditions on both levels from early on. We just need to verify what  is the behavior of Agent when conditions are defined on both levels at the same time. I guess there is some kind of priority checking that  takes place which we should document clearly :).

**Comment by ChrsMark** [comment]
Thanks for pointing this out @jsoriano! Yes, let's focus on https://github.com/elastic/kibana/issues/108525 for the `condition`s part :).

**Comment by ishleenk17** [comment]
As per Kyles [comment](https://github.com/elastic/kibana/issues/139900#issuecomment-1258364905) here, looks like having a generic raw yml box is not being looked at for near future. 
In that case all of these processors, tags, condition addition has to be taken up individually. 
@ruflin @gizas : Please share your thoughts here

**Comment by gizas** [comment]
Added a follow up https://github.com/elastic/kibana/issues/139900#issuecomment-1259128227 .
I would like to clarify how soonish can any kind of such changes start going into roadmap. 

Additionally processors are a little different than conditions, because can leave for start only in the top level (if that eases the implementation) and do not interfere with any existing data stream field. So the text box for conditions can start and independently continue the discussions for any new cases like processors that can be more complex

FYI exposing conditions is a critical thing for cloudnative team if we want to support auto-discovery feature in managed agent based on them

**Comment by ChrsMark** [comment]
@gizas @ishleenk17 @kpollich let's use https://github.com/elastic/kibana/issues/108525 for the `condition`s specific topic since it's kind of different one.

**Comment by ishleenk17** [comment]
If we are not taking the generic approach of raw yaml, it would be good to carry on discussions for processors/tags here and conditions in the other [thread](https://github.com/elastic/kibana/issues/108525).

**Comment by nimarezainia** [comment]
@ishleenk17 Consistency of input processors across all integrations is a goal but we won't be able to address this in the 8.6 timeframe.

What we have done (based on customer requirement) has been to ensure that some of the top integrations already have implemented tags&processors for their datastreams. is there a specific customer request we need to consider? if not we should punt this to a later release and ensure the technical design is appropriate.

We also do plan to address the Global processors on a per policy basis via: https://github.com/elastic/beats/issues/29459

**Comment by ishleenk17** [comment]
@nimarezainia , there are a couple of reasons why we think having this consistency of processors/tags is important: 

- There have been couple of SDH's/customer asks for this enhancement. 
- For all the new integrations we are building this has been an ask in PRD's
- Solution architects have reached out stating importance of having these while being on call with the customer


> if not we should punt this to a later release and ensure the technical design is appropriate.

I agree, the end to end technical design and challenges should be thought through. We will plan to close that in this iteration, post that I suppose we should prioritize this activity.

cc: @rameshelastic @lalit-satapathy

**Comment by nimarezainia** [comment]
@ishleenk17 I agree that we need this type of consistency across all integrations and the proposal to do it via fleet seems to be lowest effort approach. Regarding customer requests though, we have addressed those for the most part by modifying the individual packages - so I think there shoudl be less urgency in that sense.

Based on the lack of urgency on this I don' want to disrupt the work/planning that has already started  for 8.6 and we will try and pursiue the correct implementation in 8.7 (once prioritized amongst other asks there)

**Comment by ishleenk17** [comment]
> we will try and pursiue the correct implementation in 8.7 (once prioritized amongst other asks there)

Hello @nimarezainia , wanted to check if we will be prioritizing this for 8.7 ?

**Comment by ishleenk17** [comment]
@nimarezainia : There have been a couple of requests for processors in integrations yet again. 
This time the ask came in for processors in Redis. 
Can we look into this issue and take it up for 8.9 by fixing it through [Fleet](https://github.com/elastic/elastic-package/issues/949#issuecomment-1262753167)? It will help us cater to such requests in general across integrations.
cc: @rameshelastic @lalit-satapathy  @ruflin @mukeshelastic

**Comment by nimarezainia** [comment]
@ishleenk17 our 8.9 is over subscribed. I have added this as a lower priority item for 8.9 but we may have to consider 8.10 or later.

(fyi  @kpollich )

**Comment by jlind23** [comment]
@andresrc for this is has been push out to alter sprint due to competing priorities. 
If this is a high priority on your end feel free to have someone from your team pushing a PR and I will assign someone to review it.

**Comment by francescaforza1983** [comment]
Hello, my customer Telefonica Germany (1,7M, one of the biggest cloud customers in EMEA) also asks for something similar: https://github.com/elastic/enhancements/issues/18550

**Comment by nimarezainia** [comment]
The UX proposal for this, as was developed for some of the most utilized integrations, is here: https://docs.google.com/document/d/18x1q_jog3_xgCdsU20wVZcyZz1_ZiI4pXGE5ZMma6Ho/edit?usp=sharing

I'm moving this out of PM definition into tech.

**Comment by kpollich** [comment]
I've created https://github.com/elastic/kibana/issues/170336 to capture the plan for adding default field appending logic for all data streams to Fleet

**Comment by kpollich** [comment]
Closing in favor of https://github.com/elastic/kibana/issues/170336
